---
- name: Full Cluster Deployment
  hosts: localhost
  connection: local
  become: yes
  vars:
    node_role: "{{ lookup('env', 'NODE_ROLE') | default('unknown') }}"
    master_ip: "{{ lookup('env', 'MASTER_IP') | default('127.0.0.1') }}"
    token: "{{ lookup('env', 'TOKEN') | default('abcdef.1234567890abcdef') }}"

  roles:
    - role: kubernetes
    - role: monitoring
      when: node_role == "master" # Le monitoring ne s'installe que sur le Master
