---
- name: Full Master Deployment (K8s + Monitoring)
  hosts: localhost  
  connection: local 
  become: yes
   vars:
    # Cette variable récupère la valeur passée par -e "master_ip_extra=..."
    # Si rien n'est passé, elle vaut 127.0.0.1 par défaut
    master_ip: "{{ master_ip_extra | default('127.0.0.1') }}"
    token: "abcdef.1234567890abcdef"
  roles:
    - kubernetes
    - monitoring
