- name: Full Cluster Deployment
  hosts: localhost
  connection: local
  become: yes

  vars:
    node_role: "{{ node_role }}"
    master_ip: "{{ master_ip }}"
    token: "{{ token }}"
    pod_network_cidr: "192.168.0.0/16"

  pre_tasks:
    - name: Validate node_role
      fail:
        msg: "node_role must be master or worker"
      when: node_role not in ["master", "worker"]

  roles:
    - role: kubernetes
    - role: monitoring
      when: node_role == "master"
