---
- name: Full Kubernetes Cluster Deployment with Enhanced Error Handling
  hosts: localhost
  connection: local
  become: yes
  
  # Variables are passed from Heat/ansible-pull via -e (extra-vars)
  vars:
    k8s_version: "1.29"
    calico_version: "v3.27.0"
    # Default values for optional vars
    pod_network_cidr: "{{ pod_network_cidr | default('192.168.0.0/16') }}"
    storage_path: "{{ storage_path | default('/mnt/k8s-storage') }}"

  pre_tasks:
    - name: "CRITICAL CLEANUP: Remove corrupted files and fix apt locks"
      shell: |
        rm -f /tmp/cri-dockerd.deb
        rm -f /var/lib/dpkg/lock*
        rm -f /var/lib/apt/lists/lock*
        rm -f /var/cache/apt/archives/lock
        dpkg --configure -a
      ignore_errors: yes
      changed_when: false

    - name: "VALIDATION: Ensure node_role is set correctly"
      assert:
        that:
          - node_role is defined
          - node_role in ["master", "worker"]
        fail_msg: "node_role must be 'master' or 'worker'. Currently: {{ node_role | default('undefined') }}"

    - name: "VALIDATION: Ensure master_ip is provided for workers"
      assert:
        that:
          - (node_role == 'master') or (master_ip is defined and master_ip != "")
        fail_msg: "master_ip is required when node_role is 'worker'."

    - name: "Display deployment info"
      debug:
        msg:
          - "Deploying as: {{ node_role }}"
          - "Targeting Master: {{ master_ip | default('Self') }}"
          - "Network: {{ pod_network_cidr }}"

  roles:
    - role: kubernetes
    - role: monitoring
      when: node_role == "master"
